feta: finish dtkbluetooth
linuxdeepin/dtkbluetooth pull request #10
Opened 2023-02-16 08:37 UTC by ComixHe

Log: 完成dtkbluetooth

2023-02-17 04:18 UTC, asterwyx requested changes

2023-02-17 04:18 UTC, asterwyx commented on include/dbluetoothobexmanager.h
>      Q_PROPERTY(bool available READ available);
那就应该加CONSTANT

2023-02-17 04:18 UTC, asterwyx commented on include/dbluetoothobexsession.h
> +    Q_PROPERTY(QDir root READ root);
标CONSTANT

2023-02-17 04:18 UTC, asterwyx commented on include/dbluetoothobextransfer.h
> +    enum class TransferStatus { Queued, Active, Suspended, Complete, Error };
Q_ENUM可以作用在enum class上吗？

2023-02-17 04:18 UTC, asterwyx commented on src/DBus/btobexdispatcher.cpp
> -        Q_EMIT objectPushAdded(path);
改成if .. if..的形式

2023-02-17 04:18 UTC, asterwyx commented on src/DBus/dagentmanagerinterface.cpp
> +    m_inter = new DDBusInterface(Service, "/org/bluez", QLatin1String(BlueZAgentManagerInterface), Connection, this);
统一用法

2023-02-17 04:18 UTC, asterwyx commented on src/DBus/ddeviceinterface.cpp
> +    const auto &Connection = QDBusConnection::systemBus();
不推荐用引用

2023-02-17 04:18 UTC, asterwyx commented on src/DBus/dobextransferinterface.cpp
>      auto Connection = QDBusConnection::systemBus();
统一用法

2023-02-17 04:18 UTC, asterwyx commented on src/DBus/dobextransferinterface.cpp
> +                    removed();
少了Q_EMIT

2023-02-17 04:18 UTC, asterwyx commented on src/dbluetoothdeviceinfo_p.h
> +    quint16 Appearance;
改成小写

2023-02-20 01:54 UTC, Groveer submitted a review, later dismissed

2023-02-20 01:54 UTC, Groveer commented on CMakeLists.txt
> +find_package(Dtk REQUIRED COMPONENTS Core DBus Bluetooth)
写错？

2023-02-20 01:54 UTC, Groveer commented on include/dbluetoothdeviceinfo.h
>      DBluetoothDeviceInfo(const QBluetoothDeviceInfo &other);
重复

2023-02-20 02:09 UTC, ComixHe commented on include/dbluetoothdeviceinfo.h
>      DBluetoothDeviceInfo(const QBluetoothDeviceInfo &other);
这个文件已经删除了，需要刷新一下pr

2023-02-20 02:10 UTC, ComixHe commented on CMakeLists.txt
> +find_package(Dtk REQUIRED COMPONENTS Core DBus Bluetooth)
这里已经修改了，也需要刷新一下pr

2023-02-20 02:19 UTC, asterwyx commented on include/dbluetoothagent.h
> -
用enum加上Q_ENUM的方式比较好吧。

2023-02-20 02:58 UTC, asterwyx approved these changes

2023-02-20 02:59 UTC, merged