feat: add DAdapter class
linuxdeepin/dtkbluetooth pull request #3
Opened 2023-01-12 09:15 UTC by ComixHe

同时添加信号分发相关类

Log:添加DAdapter类

2023-01-12 09:36 UTC, asterwyx commented on include/DAdapter.h
> +public slots:
Q_SLOT

2023-01-12 09:36 UTC, asterwyx commented on include/DAdapter.h
> +signals:
Q_SIGNALS

2023-01-12 09:37 UTC, asterwyx commented on include/DAdapter.h
> +    Q_DECLARE_PRIVATE(DAdapter);
用D_DECLARE_PRIVATE

2023-01-12 09:37 UTC, asterwyx commented on include/DAdapter.h
> +    QScopedPointer<DAdapterPrivate> d_ptr;
可以删除

2023-01-12 09:39 UTC, asterwyx commented on src/DAdapter_p.h
> +class DAdapterPrivate : public QObject
继承自DObjectPrivate

2023-01-12 09:39 UTC, asterwyx commented on include/DAdapter.h
> +class DAdapter : public QObject
加一个基类,继承自DObject

2023-01-12 09:40 UTC, asterwyx commented on src/DAdapter_p.h
> +    Q_DECLARE_PUBLIC(DAdapter)
用D_DECLARE_PUBLIC

2023-01-12 09:40 UTC, asterwyx commented on src/DAdpter.cpp
> +#include "DAdapter_p.h"
全小写命名

2023-01-12 09:43 UTC, asterwyx commented on src/DAdpter.cpp
> +    , adapterPath("/com/deepin/Fakebluez/hci" + QString::number(adapterId))
改成/org/deepin/fakebluez/hci

2023-01-12 09:44 UTC, asterwyx commented on src/DAdpter.cpp
> +    Q_D(const DAdapter);
D_DC

2023-01-12 09:48 UTC, asterwyx commented on src/DBus/BTDispatcher.cpp
> +                emit AdapterAdded(path);
Q_EMIT

2023-01-12 09:51 UTC, asterwyx commented on src/DBus/BTDispatcher.h
> +static BluetoothDispatcher *BTDispatcher{nullptr};
删掉,不暴露出去

2023-01-12 09:52 UTC, asterwyx commented on src/DBus/BTDispatcher.h
> +    static BluetoothDispatcher *getGlobalDispatcher();
在这个函数里面定义静态变量然后抛出来

2023-01-13 01:10 UTC, Groveer reviewed
+1

2023-01-13 06:01 UTC, asterwyx commented on include/dadapter.h
> +class DAdapter : public QObject, DObject
检查一下这种写法的继承是不是public的

2023-01-13 06:01 UTC, asterwyx commented on include/dadapter.h
> +
这里的空行去掉

2023-01-13 06:03 UTC, asterwyx commented on include/dtkbluetoothtypes.h
> +using ObjectMap = QMap<QDBusObjectPath, QVariantMap>;
这里为什么一定要导出去吗

2023-01-13 06:03 UTC, asterwyx commented on include/dtkbluetoothtypes.h
> +using ObjectMap = QMap<QDBusObjectPath, QVariantMap>;
用户不用到的类型不要放在公共头文件里面

2023-01-13 06:04 UTC, asterwyx commented on src/DBus/btdispatcher.cpp
> +BluetoothDispatcher &BluetoothDispatcher::Instance()
instance小写开头

2023-01-13 06:05 UTC, asterwyx commented on src/DBus/btdispatcher.h
> +    void AdapterAdded(const QDBusObjectPath adapter);
这里的信号用驼峰命名法

2023-01-13 06:06 UTC, asterwyx commented on src/DBus/dadapterinterface.cpp
> +    const auto &Interface = QLatin1String(BlueZAdapterInterface);
这两个一样的就不用放在宏定义里面

2023-01-13 06:07 UTC, asterwyx commented on src/DBus/dadapterinterface.h
> +
空行删掉

2023-01-13 06:08 UTC, asterwyx commented on src/DBus/dbussignaldispatcher.h
> +    virtual ~DBusSignalDispatcher() override = default;
写了override就不需要写virtual

2023-01-13 06:09 UTC, asterwyx commented on src/DBus/dobjectmanagerinterface.cpp
> +                           Q_EMIT this->InterfacesRemoved(interfaces);
检查一下有没有相同的变量内容

2023-01-13 06:12 UTC, asterwyx commented on tests/fakeDBus/demoservice.cpp
> +    Q_Q_EMIT DockedChanged(docked);
这里的宏是错误的

2023-01-13 06:12 UTC, asterwyx commented on tests/fakeDBus/demoservice.cpp
> +            Q_Q_EMIT UserNew(user.user_id, user.path);
宏错误

2023-01-13 06:13 UTC, asterwyx commented on tests/fakeDBus/demoservice.cpp
>          return;
这三个文件全部移除

2023-01-13 06:40 UTC, asterwyx commented on misc/DtkBluetoothConfig.cmake.in
> -find_dependency(Qt@QT_VERSION_MAJOR@ COMPONENTS Core DBus Network)
检查从模板出来的文件是不是正确的

2023-01-13 06:45 UTC, asterwyx requested changes

2023-01-13 06:45 UTC, asterwyx commented on src/DBus/dobjectmanagerinterface.cpp
> +    Connection.connect(service, Path, Interface, "InterfacesAdded", this, SLOT([this](const ObjectMap &interfaces) {
这种写法是不是有效的,可以验证一下.

2023-01-13 06:45 UTC, asterwyx commented on src/DBus/types.h
> +// SPDX-FileCopyrightText: 2023 UnionTech Software Technology Co., Ltd.
这个文件的名字太简单了

2023-01-13 06:45 UTC, asterwyx commented on src/DBus/utils.h
> +// SPDX-FileCopyrightText: 2023 UnionTech Software Technology Co., Ltd.
同理,这个文件的名字也太简单了,以后可能会开放私有头文件,要考虑到这个问题,虽然目前不开放.

2023-01-13 08:54 UTC, asterwyx commented on misc/DtkBluetoothConfig.cmake.in
> +find_package(QT NAMES Qt5 REQUIRED COMPONENTS Core)
这一句应该放在编译dtkbluetooth的CMakeList.txt

2023-01-13 09:28 UTC, asterwyx approved these changes

2023-01-13 09:28 UTC, merged