feat: finish DAgent, DDevice and DManager
linuxdeepin/dtkbluetooth pull request #9
Opened 2023-02-13 09:24 UTC by ComixHe

Log: 完成DAgent, DDevice和DManager

2023-02-13 09:50 UTC, Groveer commented
/+1

2023-02-14 03:01 UTC, asterwyx requested changes

2023-02-14 03:01 UTC, asterwyx commented on include/dbluetoothagent.h
> +#endif
结尾空行没有加。

2023-02-14 03:01 UTC, asterwyx commented on include/dbluetoothdeviceinfo.h
> +#endif
结尾空行。

2023-02-14 03:01 UTC, asterwyx commented on include/dbluetoothmanager.h
> +    QSharedPointer<DAdapter> specificAdapter(qint64 adapterId);
建议改成adapterFromId

2023-02-14 03:01 UTC, asterwyx commented on src/dbluetoothagent.cpp
> +DBLUETOOTH_END_NAMESPACE
结尾空行。

2023-02-14 03:01 UTC, asterwyx commented on src/dbluetoothagentadaptor.cpp
> +DBLUETOOTH_END_NAMESPACE
结尾空行。

2023-02-14 03:01 UTC, asterwyx commented on src/dbluetoothagentadaptor.h
> +#endif
结尾空行。

2023-02-14 03:01 UTC, asterwyx commented on src/dbluetoothdevice.cpp
> -    connect(d->m_device, &DDeviceInterface::nameChanged, this, &DDevice::nameChanged);
不会改变的属性要标CONSTANT。

2023-02-14 03:01 UTC, asterwyx commented on src/dbluetoothdeviceinfo.cpp
> +DBLUETOOTH_END_NAMESPACE
结尾空行。

2023-02-14 03:01 UTC, asterwyx commented on src/dbluetoothutils.h
> +    const QString idStr = path.split("/").last().mid(2);
写个注释例子在这里

2023-02-14 03:01 UTC, asterwyx commented on src/dbluetoothutils.h
>      const auto &rawDeviceStr = "/dev_" + device.replace(":", "_");
写个例子

2023-02-14 03:01 UTC, asterwyx commented on src/dbluetoothutils.h
> +inline transferStatus stringToenum(QString statusStr)
```suggestion
inline transferStatus stringToEnum(QString statusStr)
```

2023-02-14 05:20 UTC, asterwyx requested changes

2023-02-14 05:20 UTC, asterwyx commented on src/DBus/ddeviceinterface.h
> +    Q_PROPERTY(quint16 appearance READ appearance)
不变的PROPERTY加CONSTANT

2023-02-14 05:35 UTC, asterwyx approved these changes

2023-02-14 05:35 UTC, merged